#!/usr/bin/env python3
"""Convert a downloaded linux-usb.org usb.ids into USB Prober's vendor table."""

import argparse
from pathlib import Path
import re


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("usb_ids", type=Path, help="Downloaded usb.ids file")
    args = parser.parse_args()
    vendors = {}
    metadata = []
    for line in args.usb_ids.read_bytes().splitlines():
        if line.startswith((b"# Version:", b"# Date:")):
            metadata.append(line.decode("ascii"))
        match = re.fullmatch(rb"([0-9a-fA-F]{4})[ \t]+(.+)", line)
        if not match:
            continue  # Skip comments, indented products/interfaces and class tables.
        vendor_id = int(match[1], 16)
        # Some upstream product names use legacy encodings. Decode each vendor
        # independently so those rows cannot corrupt or prevent a vendor update.
        try:
            name = match[2].decode("utf-8").strip()
        except UnicodeDecodeError:
            name = match[2].decode("latin-1").strip()
        if vendor_id in vendors or not name or "|" in name:
            raise ValueError(f"Invalid or duplicate vendor entry: {line!r}")
        vendors[vendor_id] = name
    if len(vendors) < 2000 or len(metadata) != 2:
        raise ValueError("Incomplete USB ID database; vendor table left unchanged")
    output = Path(__file__).resolve().parent.parent / "USBVendors.txt"
    header = [
        "# USB vendor names from http://www.linux-usb.org/usb.ids",
        "# Maintained by Stephen J. Gowdy <linux.usb.ids@gmail.com>",
        *metadata,
        "# Generated by Scripts/update-usb-vendors.py; decimal vendor ID|UTF-8 name",
    ]
    rows = [f"{vendor_id}|{name}" for vendor_id, name in sorted(vendors.items())]
    output.write_text("\n".join(header + rows) + "\n", encoding="utf-8")
    print(f"Updated {output.name}: {len(vendors)} vendors")


if __name__ == "__main__":
    main()
